# Generated by Django 2.0.7 on 2018-07-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='document',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
