# Generated by Django 2.1.1 on 2018-11-10 01:31

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20180730_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='upload.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='document',
            field=models.FileField(upload_to=upload.models.content_file_name, verbose_name=''),
        ),
    ]
