# Generated by Django 2.1.1 on 2018-11-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('upload', '0005_auto_20181109_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
