# Generated by Django 2.1.1 on 2018-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20181109_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
