# Generated by Django 2.0.7 on 2018-11-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_student_github_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='github_username',
        ),
        migrations.AddField(
            model_name='student',
            name='github_accounts',
            field=models.ManyToManyField(to='upload.GitHubAccount'),
        ),
    ]
