# Generated by Django 2.0.7 on 2019-02-18 15:32

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20181112_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=upload.models.content_file_name, verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='document',
        ),
        migrations.AddField(
            model_name='submission',
            name='files',
            field=models.ManyToManyField(to='upload.File'),
        ),
    ]
